I'm sorry, but an uncaught exception occurred.

While running game code:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\faizk\\Downloads\\renpy-8.3.4-sdk\\Study Battle1\\game\\saves\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\main.py", line 666, in main
    renpy.persistent.update(True)
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\persistent.py", line 434, in update
    save()
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "C:\Users\faizk\Downloads\renpy-8.3.4-sdk\renpy\savelocation.py", line 433, in save_persistent
    self.persistent_mtime = os.path.getmtime(fn)
  File "lib/python3.9/genericpath.py", line 55, in getmtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\faizk\\Downloads\\renpy-8.3.4-sdk\\Study Battle1\\game\\saves\\persistent'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Study Battle 1.0
Fri Dec 13 13:51:10 2024
