I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 129, in script call
    call battle from _call_battle
  File "game/battle.rpy", line 482, in script
    $renpy.pause(1.0,hard=True)
  File "game/battle.rpy", line 482, in <module>
    $renpy.pause(1.0,hard=True)
  File "game/battle.rpy", line 306, in execute
    screen healths:
  File "game/battle.rpy", line 306, in execute
    screen healths:
  File "game/battle.rpy", line 307, in execute
    frame at alpha_dissolve:
  File "game/battle.rpy", line 312, in execute
    text "{i}[user] & [sib]{/i}" xalign 0.135 yalign 0.22 font "fonts/rexlia rg.otf"
NameError: Name 'user' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 129, in script call
    call battle from _call_battle
  File "game/battle.rpy", line 482, in script
    $renpy.pause(1.0,hard=True)
  File "D:\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/battle.rpy", line 482, in <module>
    $renpy.pause(1.0,hard=True)
  File "D:\renpy-8.3.2-sdk\renpy\exports\statementexports.py", line 194, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "D:\renpy-8.3.2-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.3.2-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.3.2-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy-8.3.2-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.2-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.2-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.2-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "D:\renpy-8.3.2-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy-8.3.2-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "D:\renpy-8.3.2-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/battle.rpy", line 306, in execute
    screen healths:
  File "game/battle.rpy", line 306, in execute
    screen healths:
  File "game/battle.rpy", line 307, in execute
    frame at alpha_dissolve:
  File "game/battle.rpy", line 312, in execute
    text "{i}[user] & [sib]{/i}" xalign 0.135 yalign 0.22 font "fonts/rexlia rg.otf"
  File "D:\renpy-8.3.2-sdk\renpy\text\text.py", line 2093, in _scope
    return self.set_text(self.text_parameter, scope, self.substitute, update)
  File "D:\renpy-8.3.2-sdk\renpy\text\text.py", line 2132, in set_text
    i, did_sub = renpy.substitutions.substitute(i, scope, substitute) # type: ignore
  File "D:\renpy-8.3.2-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "D:\renpy-8.3.2-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "D:\renpy-8.3.2-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "D:\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "D:\renpy-8.3.2-sdk\renpy\substitutions.py", line 313, in __getitem__
    raise NameError("Name '{}' is not defined.".format(key))
NameError: Name 'user' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090901
Study Battle Alpha 1.0
Sun Dec  1 07:32:02 2024
